export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <header className="p-6 bg-orange-600">Header</header>
        {children}
        <footer className="p-6 bg-orange-600">Footer</footer>
      </body>
    </html>
  )
}
